### ISSUE TITLE
Issue with scoped keyframes

### ISSUE THREAD

**Issue by giokaxo** [vuejs/docs-next#949]
Hello, I've found an issue with scoped keyframes.

For example:
```scss
.loading-icon[data-v-38b53385] {
    @keyframes playback-loading {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
}
```
This snippet is compiled to
```css
.loading-icon[data-v-38b53385] {
  animation: playback-loading-38b53385 3s infinite linear;
  position: absolute;
  top: 0;
  clip-path: circle(3rem at center center);
}
@keyframes playback-loading-38b53385 {
  0%[data-v-38b53385] {
      transform: rotate(0deg);
  }
  100%[data-v-38b53385] {
      transform: rotate(360deg);
  }
}
```

The fix I've found is to use `:global` pseudo element, but I don't think it is supposed to work this way:
```scss
.loading-icon[data-v-38b53385] {
    @keyframes playback-loading {
        :global(0%) {
            transform: rotate(0deg);
        }

        :global(100%) {
            transform: rotate(360deg);
        }
    }
}
```
